# Release drafter configuration https://github.com/release-drafter/release-drafter#configuration
# Emojis were chosen to match the https://gitmoji.carloscuesta.me/

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: ":rocket: Features"
    labels: [enhancement, feature]
  - title: ":wrench: Fixes & Refactoring"
    labels: [bug, refactoring, bugfix, fix, pref]
  - title: ":package: Build System & CI/CD"
    labels: [build, ci, testing]
  - title: ":boom: Breaking Changes"
    labels: [breaking]
  - title: ":pencil: Documentation"
    labels: [documentation, docs]
  - title: ":arrow_up: Dependencies updates"
    labels: [dependencies, chore]

template: |
  👋 Hello and welcome to the release notes for P3G v$NEXT_PATCH_VERSION! We're excited to share some new updates that we believe will enhance your experience with P3G.
  
  For detailed information, please visit our official documentation: [P3G Documentation](https://p3g.zeeland.top)

  To see the code, report issues, or contribute, check out our GitHub repository: [P3G on GitHub](https://github.com/Undertone0809/p3g)

  ## What’s Changed

  $CHANGES

  ## :busts_in_silhouette: List of contributors

  $CONTRIBUTORS
